spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parceiros?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: maria
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
